// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpnf6gbiUiAI4RHbkeSiymkEIMwI_qiI',
    appId: '1:583263135547:web:d0e4cd564476f6429df91e',
    messagingSenderId: '583263135547',
    projectId: 'hadaia-42cb7',
    authDomain: 'hadaia-42cb7.firebaseapp.com',
    storageBucket: 'hadaia-42cb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeD0fNxytX5yiwEAYjfj2LGSuHLbdhrus',
    appId: '1:583263135547:android:331b91498d43ea079df91e',
    messagingSenderId: '583263135547',
    projectId: 'hadaia-42cb7',
    storageBucket: 'hadaia-42cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzGKCd5TinIy_bxyiUU7a25OM3qVYib-0',
    appId: '1:583263135547:ios:0b8c09cdb06c7f579df91e',
    messagingSenderId: '583263135547',
    projectId: 'hadaia-42cb7',
    storageBucket: 'hadaia-42cb7.appspot.com',
    iosBundleId: 'com.example.hadaia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzGKCd5TinIy_bxyiUU7a25OM3qVYib-0',
    appId: '1:583263135547:ios:0b8c09cdb06c7f579df91e',
    messagingSenderId: '583263135547',
    projectId: 'hadaia-42cb7',
    storageBucket: 'hadaia-42cb7.appspot.com',
    iosBundleId: 'com.example.hadaia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpnf6gbiUiAI4RHbkeSiymkEIMwI_qiI',
    appId: '1:583263135547:web:d0690e788a2678db9df91e',
    messagingSenderId: '583263135547',
    projectId: 'hadaia-42cb7',
    authDomain: 'hadaia-42cb7.firebaseapp.com',
    storageBucket: 'hadaia-42cb7.appspot.com',
  );
}
